Changing peers to nodes. This is inline with both the Android and iOS…
meshtastic/js pull request #81
Opened 2024-03-11 20:17 UTC by davidlpower

Align web client to use the same terminology for nodes. This is inline with both the Android and iOS Apps.

**Primary Change**

- Changing peers to nodes.

**Important**

- This PR would need to be merged and the JS package included in the Web App before we merge [meshtastic/web/pull/168](https://github.com/meshtastic/web/pull/168)

2024-03-11 20:54 UTC, davidlpower commented on src/meshDevice.ts
> +      "📻 Resetting Nodes",
Good call out. Updated.

2024-03-11 23:01 UTC, sachaw approved these changes

2024-03-13 11:01 UTC, sachaw requested changes

2024-03-14 17:53 UTC, davidlpower commented on jsr.json
> +  "version": "2.2.25-0",
Thanks for explaining. I've amended the commit with this change.

2024-03-14 21:58 UTC, sachaw commented
sorry, last thing, please bump the version in package.json too

2024-03-15 08:10 UTC, davidlpower commented
> sorry, last thing, please bump the version in package.json too

Done. :D

2024-03-15 08:41 UTC, merged